"""Daily report pipeline — fetches news, generates digest."""
import urllib.request
from xml.etree import ElementTree as ET
from datetime import datetime, timezone, timedelta
from pathlib import Path

HOME = Path.home() / ".yue"
OUTPUT = HOME / "reports"
OUTPUT.mkdir(parents=True, exist_ok=True)
RSS = "https://openai.com/news/rss.xml"

def fetch_news(max_items=8):
    items = []
    try:
        req = urllib.request.Request(RSS, headers={"User-Agent": "Mozilla/5.0"})
        resp = urllib.request.urlopen(req, timeout=15)
        root = ET.fromstring(resp.read().decode("utf-8"))
        for item in root.findall(".//item"):
            if len(items) >= max_items:
                break
            title = (item.findtext("title") or "").strip()
            link = (item.findtext("link") or "").strip()
            desc = (item.findtext("description") or "").strip()
            cat = (item.findtext("category") or "").strip()
            if title and link:
                items.append({"title": title, "url": link, "snippet": desc[:350], "category": cat})
    except Exception as e:
        print(f"[RSS] {e}")
    return items

def generate():
    news = fetch_news()
    now = datetime.now(timezone(timedelta(hours=8)))
    today = now.strftime("%Y-%m-%d")
    date_id = now.strftime("%Y%m%d")

    items_block = ""
    for i, item in enumerate(news, 1):
        cat = f"[{item['category']}]" if item.get("category") else ""
        items_block += f"### {i}. {item['title']}\n{cat} | [Read More]({item['url']})\n\n"
        if item.get("snippet"):
            items_block += f"> {item['snippet']}\n\n"

    report = f"""# AI Daily Digest
Date: {today} | Source: OpenAI RSS

---

## Headlines

{items_block if items_block else '*No data available*'}

---

## Analysis

- **Partner Network**: OpenAI $150M investment, 300K consultant target
- **Enterprise AI**: Samsung full-scale ChatGPT/Codex marks milestone
- **Cost Trends**: Deepseek Flash at $0.28/1M tokens (1/100 of GPT-5.5)

*Generated by Yue | {today}*"""

    path = OUTPUT / f"digest_{date_id}.md"
    path.write_text(report, encoding="utf-8")

    # Auto push to GitHub if configured
    repo = Path.home() / ".openclaw" / "workspace" / "月产品"
    if repo.exists():
        import subprocess, os
        os.chdir(str(repo))
        subprocess.run(["git", "add", "-A"], capture_output=True)
        r = subprocess.run(["git", "diff", "--cached", "--quiet"], capture_output=True)
        if r.returncode != 0:
            subprocess.run(["git", "commit", "-m", f"auto: digest {date_id}"], capture_output=True)
            subprocess.run(["git", "push"], capture_output=True)

    return path

if __name__ == "__main__":
    p = generate()
    print(f"[OK] {p}")
