#!/usr/bin/env python3
"""Report Generator - Autonomous content pipeline. Fetches RSS, generates digest, pushes to GitHub."""
import sys, os, re
from datetime import datetime, timezone, timedelta
from pathlib import Path
from xml.etree import ElementTree as ET
import urllib.request

BASE_DIR = Path(os.path.expanduser("~/.openclaw/workspace/月产品"))
OUTPUT_DIR = BASE_DIR / "products" / "docs"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
RSS_URL = "https://openai.com/news/rss.xml"

def fetch_news(max_items=8):
    items = []
    try:
        req = urllib.request.Request(RSS_URL, headers={"User-Agent": "Mozilla/5.0"})
        resp = urllib.request.urlopen(req, timeout=15)
        xml = resp.read().decode("utf-8")
        root = ET.fromstring(xml)
        for item in root.findall(".//item"):
            if len(items) >= max_items:
                break
            title = (item.findtext("title") or "").strip()
            link = (item.findtext("link") or "").strip()
            desc = (item.findtext("description") or "").strip()
            cat = (item.findtext("category") or "").strip()
            if title and link:
                items.append({
                    "title": title, "url": link,
                    "snippet": desc[:350], "category": cat
                })
    except Exception as e:
        print(f"  RSS fetch: {e}")
    return items

def generate_report(news_items):
    now = datetime.now(timezone(timedelta(hours=8)))
    today = now.strftime("%Y-%m-%d")
    items_block = ""
    for i, item in enumerate(news_items, 1):
        items_block += f"### {i}. {item['title']}\n"
        cat = f"[{item['category']}]" if item.get("category") else ""
        items_block += f"{cat} | [Read More]({item['url']})\n\n"
        if item.get("snippet"):
            items_block += f"> {item['snippet']}\n\n"
    return f"""# AI Daily Digest
Date: {today}
Source: OpenAI RSS

---

## Headlines

{items_block if items_block else "*No data*"}

---

## Analysis

### Partner Network
$150M investment, 300K consultants target. AI moves from technology to service delivery.

### Enterprise AI
Samsung full-scale ChatGPT/Codex deployment marks enterprise AI milestone.

### Cost
Deepseek V4 Flash at $0.28/1M tokens (1/100 of GPT-5.5). Autonomous production at near-zero marginal cost.

---

*Generated by Yue | {today}*"""

def save_report(content):
    date_id = datetime.now(timezone(timedelta(hours=8))).strftime("%Y%m%d")
    path = OUTPUT_DIR / f"AI_Daily_{date_id}.md"
    path.write_text(content, encoding="utf-8")

    # Also update readme
    readme = BASE_DIR / "README.md"
    text = readme.read_text(encoding="utf-8") if readme.exists() else ""
    listing = "## Latest Products\n"
    for f in sorted(OUTPUT_DIR.glob("*.md"), reverse=True)[:5]:
        ts = datetime.fromtimestamp(f.stat().st_mtime).strftime("%m-%d %H:%M")
        listing += f"- [{f.stem.replace('_', ' ')}](products/docs/{f.name}) ({ts})\n"
    if "## Latest Products" in text:
        text = re.sub(r"## Latest Products\n.*?(?=\n## |$)", listing + "\n", text, flags=re.DOTALL)
    else:
        text += "\n" + listing + "\n"
    readme.write_text(text, encoding="utf-8")

    # Git push
    os.chdir(str(BASE_DIR))
    import subprocess
    subprocess.run(["git", "add", "-A"], capture_output=True)
    r = subprocess.run(["git", "diff", "--cached", "--quiet"], capture_output=True)
    if r.returncode != 0:
        subprocess.run(["git", "commit", "-m", f"auto: daily digest {date_id}"], capture_output=True)
        p = subprocess.run(["git", "push"], capture_output=True, text=True)
    return path

def generate_daily_report():
    print("  [1/3] Fetching news...")
    news = fetch_news()
    print(f"  [2/3] {len(news)} articles, generating report...")
    report = generate_report(news)
    path = save_report(report)
    print(f"  [3/3] Saved: {path.name}")
    return path

if __name__ == "__main__":
    generate_daily_report()
